media:
  input: assets
  output: /assets

content:
  - name: galeria
    label: Galería
    type: collection
    path: assets/img
    fields:
      - name: title
        label: Título
        type: string
      - name: image
        label: Imagen
        type: image

  - name: videos
    label: Videos
    type: collection
    path: assets/video
    fields:
      - name: title
        label: Título
        type: string
      - name: video
        label: Video
        type: file