backend:
  name: github
  repo: leitmixproducciones/leitmix-producciones-web
  branch: master

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "galeria"
    label: "Galeria"
    folder: "assets/img"
    create: true
    fields:
      - label: "Imagen"
        name: "image"
        widget: "image"
      - label: "Titulo"
        name: "title"
        widget: "string"
